title: Vincent Navetat - Illustrations
email: vincentnavetat@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Illustrator based in London, UK
baseurl: "/illustrations" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: vincentnavetat
github_username:  vincentnavetat

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
sass:
  sass_dir: assets/stylesheets/

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
